### ISSUE TITLE
自己紹介

### ISSUE THREAD

**Issue by hiroak** [hiroak/team_project#2]
大橋と申します。普段は、メーカでプロマネをやってます。IT初心者のため色々とご迷惑をおかけする事もあるかと思いますが、宜しくお願い致します。

**Comment by terra-yucco** [comment]
:+1:
よろしくお願いします！

![LGTM](https://lgtm.in/p/K3GbN93qq)

**Comment by terra-yucco** [comment]
では、閉じさせていただきます！

**Comment by makotomotegi** [comment]
はじめまして

**Comment by mabonki0725** [comment]
はじめまして中井です
